ekf_filter_node:
  ros__parameters:
    # Frekuensi fusi matriks (20Hz menyesuaikan kecepatan masuknya data dari STM32 & RF2O)
    frequency: 20.0
    
    # Mode 2D aktif mutlak karena robot tidak terbang (Z, Roll, Pitch diabaikan)
    two_d_mode: true
    
    # EKF mengambil alih tugas menyiarkan TF dari odom ke base_link
    publish_tf: true
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # ========================================================================
    # SAKSI UTAMA (PRIORITAS TERTINGGI): ODOMETRI LASER (RF2O)
    # ========================================================================
    odom0: /odom_rf2o
    # Matriks Konfigurasi [X, Y, Z, Roll, Pitch, Yaw, Vx, Vy, Vz, VRoll, VPitch, VYaw, Ax, Ay, Az]
    # KITA MEMPERCAYAI posisi absolut 2D (X, Y) dan orientasi (Yaw) dari pencocokan siluet LiDAR.
    # Ini adalah mata robot Anda yang mengoreksi semua selip mekanis.
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false

    # ========================================================================
    # SAKSI CADANGAN (REDUNDANSI): ODOMETRI RODA (ENCODER)
    # ========================================================================
    odom1: /odom_raw
    # KITA TIDAK MEMPERCAYAI posisi absolut roda karena bukti empiris eror selip 6.91%.
    # Kita HANYA mempercayai kecepatan translasi maju sesaat (Vx) dan kecepatan sudut (VYaw) 
    # untuk mengisi kekosongan data jika LiDAR mendadak buta.
    odom1_config: [false, false, false,
                   false, false, false,
                   true,  false, false,
                   false, false, true,
                   false, false, false]
    odom1_differential: false

    # ========================================================================
    # SAKSI INERSIA: IMU
    # ========================================================================
    imu0: /imu/data_raw
    # Kita HANYA mempercayai kecepatan rotasi (VYaw) dari giroskop MPU6050.
    # Orientasi absolut diabaikan karena absennya kompas (magnetometer).
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_remove_gravitational_acceleration: true
